version: '3'

services:
  shop-mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - "3307:3306"
    expose:
      - "3306"
    networks:
      - shop-network

  shop-laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_CONNECTION: mysql
      DB_HOST: shop-mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: 1234
    ports:
      - "8089:80"
    depends_on:
      - shop-mysql
    networks:
      - shop-network

networks:
  shop-network:
